from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Firefox()

driver.get("https://angel.co/companies")
time.sleep(3)


href = driver.find_element_by_link_text("HomeLight").get_attribute("href")
print('HomeLight:'+(href))
href = driver.find_element_by_link_text("Asana").get_attribute("href")
print('Asana:'+(href))
href = driver.find_element_by_link_text("Blekko").get_attribute("href")
print('Blekko:'+(href))
href = driver.find_element_by_link_text("LiveOps").get_attribute("href")
print('LiveOps:'+(href))
href = driver.find_element_by_link_text("Poll Everywhere").get_attribute("href")
print('Poll Everywhere:'+(href))
href = driver.find_element_by_link_text("Kapost").get_attribute("href")
print('Kapost:'+(href))
href = driver.find_element_by_link_text("Yext").get_attribute("href")
print('Yext:'+(href))
href = driver.find_element_by_link_text("GroundLink").get_attribute("href")
print('GroundLink:'+(href))
href = driver.find_element_by_link_text("LocoMobi").get_attribute("href")
print('LocoMobi:'+(href))
href = driver.find_element_by_link_text("GoodRx").get_attribute("href")
print('GoodRx:'+(href))
href = driver.find_element_by_link_text("Benchling").get_attribute("href")
print('Benchling:'+(href))
href = driver.find_element_by_link_text("Skift").get_attribute("href")
print('Skift:'+(href))
href = driver.find_element_by_link_text("Trifacta").get_attribute("href")
print('Trifacta:'+(href))
href = driver.find_element_by_link_text("Scalyr").get_attribute("href")
print('Scalyr:'+(href))
href = driver.find_element_by_link_text("Factory").get_attribute("href")
print('Factory:'+(href))
href = driver.find_element_by_link_text("Evidation Health").get_attribute("href")
print('Evidation Health:'+(href))
href = driver.find_element_by_link_text("Matternet").get_attribute("href")
print('Matternet:'+(href))
href = driver.find_element_by_link_text("Placenote").get_attribute("href")
print('Placenote:'+(href))
href = driver.find_element_by_link_text("MANOR").get_attribute("href")
print('MANOR:'+(href))
href = driver.find_element_by_link_text("Prefer").get_attribute("href")
print('Prefer:'+(href))